"""added unqiue param to Truck.unique_num

Revision ID: 510292b2ce25
Revises: 86503fbeac5f
Create Date: 2023-05-26 03:05:22.999537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510292b2ce25'
down_revision = '86503fbeac5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'truck', ['unique_num'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'truck', type_='unique')
    # ### end Alembic commands ###
