"""Added initial table

Revision ID: 86503fbeac5f
Revises: 
Create Date: 2023-05-25 12:01:28.355554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86503fbeac5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.Column('lat', sa.DECIMAL(), nullable=False),
    sa.Column('lng', sa.DECIMAL(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_id'), 'location', ['id'], unique=False)
    op.create_table('cargo',
    sa.Column('pic_up_location', sa.Integer(), nullable=False),
    sa.Column('delivery_location', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['delivery_location'], ['location.id'], ),
    sa.ForeignKeyConstraint(['pic_up_location'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_id'), 'cargo', ['id'], unique=False)
    op.create_table('truck',
    sa.Column('unique_num', sa.String(), nullable=False),
    sa.Column('current_location', sa.Integer(), nullable=False),
    sa.Column('load_capacity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['current_location'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_truck_id'), 'truck', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_truck_id'), table_name='truck')
    op.drop_table('truck')
    op.drop_index(op.f('ix_cargo_id'), table_name='cargo')
    op.drop_table('cargo')
    op.drop_index(op.f('ix_location_id'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
